### ISSUE TITLE
Where is the soloarized.jar file

### ISSUE THREAD

**Issue by jbollman7** [4lex4/intellij-platform-solarized#10]
I know I'm missing something major, but i simply cant find that jar file? Do i build that jar form the json provided in the code base? The first step assumes there is a jar, and all i need to do is load it.

**Comment by 4lex4** [comment]
[Here](https://github.com/4lex4/intellij-platform-solarized/releases) or [here](https://plugins.jetbrains.com/plugin/12784-solarized-themes/)
