### ISSUE TITLE
SolarizedLight: background color for checkbox and radio does not match the background for text fields

### ISSUE THREAD

**Issue by vlsi** [4lex4/intellij-platform-solarized#11]
Sample: <img src="https://user-images.githubusercontent.com/31143295/77685463-c42b2f80-6f9b-11ea-9efc-06eda6815484.png">

Original issue: https://github.com/weisJ/darklaf/issues/122

**Comment by 4lex4** [comment]
Reported to JetBrains: https://youtrack.jetbrains.com/issue/IDEA-236214
