### ISSUE TITLE
Solarized Light - Kotlin minor gripes 

### ISSUE THREAD

**Issue by lppedd** [4lex4/intellij-platform-solarized#12]
Using Kotlin here, and had to make minor changes to improve code readability.

- Search result & Identifier under carert: BG `#E1DBE6`
The background color was too strong, I'd say too invasive on the screen especially for Identifier under caret.

- Unused symbol: FG `#C2BCAE` / BG `#F3ECDA`
Unused symbols were not visible, I had to look at the line marker on the right.

 - Extension property: FG `#6C71C4`, removed _italic_
Reasoning to use Instance property colors for Extention property is that Extentions are applied to instances and not on classes, thus in use they're not `static`.

- Extension function call: FG `#657B83`, removed _italic_
Same color as Function call, as again, they're applied to instances and should be seen as instance functions.

- Var (mutable): Effect `#D5CFBE`
The effect was far too visible and distracting

Anyway, great themes! Those changes might just be preferences but wanted to share so you can try them 😄 

Display: BenQ PD3200U

**Comment by 4lex4** [comment]
Thanks, I will look into that.

> Reasoning to use Instance property colors for Extention property is that Extentions are applied to instances and not on classes, thus in use they're not static
> Same color as Function call, as again, they're applied to instances and should be seen as instance functions.
I agree with you, but JetBrains uses *italic* in their default themes for those stuff for some reason and I can't understand for what.

**Comment by lppedd** [comment]
> Thanks, I will look into that.

Awesome! You can even start with those values and tweak them per your choice. Those were the ones I picked after half an hour of tweaking.

> uses italic in their default themes for those stuff for some reason

Have no idea too honestly. Though usually JB developers answer on Twitter, maybe I can ask them.
