### ISSUE TITLE
"Running" activity indicator dots aren't using solarized colours?

### ISSUE THREAD

**Issue by hjst** [4lex4/intellij-platform-solarized#15]
It looks like the small "something's running" dots that are overlaid on things like the run config dropdown, or the "Run" tool window tab, are still using the default intellij bright green:

<img width="503" alt="Screenshot 2020-05-19 at 19 22 20" src="https://user-images.githubusercontent.com/330804/82364108-be375500-9a06-11ea-9019-cf742ffc3ced.png">
<img width="256" alt="Screenshot 2020-05-19 at 19 22 35" src="https://user-images.githubusercontent.com/330804/82364118-c1324580-9a06-11ea-8c33-ec5bef346106.png">

**Comment by 4lex4** [comment]
Report this to JetBrains, probably they missed making that icon themed.
