### ISSUE TITLE
Inline debug values cannot be seen in Solarized Light color theme.

### ISSUE THREAD

**Issue by uRohan** [4lex4/intellij-platform-solarized#16]
Some debug information (inline debug values) cannot be seen due to the fact that the color of the text and the background are the same.

![solarized light theme_01](https://user-images.githubusercontent.com/11392016/87947010-c21c3d80-ca70-11ea-9d94-713b0f6f2f90.png)
![Solarized light theme_02](https://user-images.githubusercontent.com/11392016/87947020-c5afc480-ca70-11ea-9630-b19d28a872d7.png)
![solarized dark theme_01](https://user-images.githubusercontent.com/11392016/87947034-ca747880-ca70-11ea-9ef2-febef9ee28ae.png)
![solarized dark theme_02](https://user-images.githubusercontent.com/11392016/87947042-ce07ff80-ca70-11ea-941a-7d85f04bc14d.png)

(IDE: IntelliJ IDEA)
(programming language: Java)

**Comment by 4lex4** [comment]
I can't fix this without breaking other things as JetBrains hardcoded those values (so they're only dependent on inline hints ones) without leaving any other options. Those are also hardly visible with IntelliJ and Darcula as well. If that's important to you, a workaround I see is to change execution line effect to border.

I'll publish the link to the ticket on JetBrains issue tracker here later.

**Comment by uRohan** [comment]
No, for me personally it is not so important. I was motivated to improve the product (I really like this theme/plugin) and thought there was a simple solution to this problem. Thanks.
