### ISSUE TITLE
Incompatible with Solarized Vim inside the terminal

### ISSUE THREAD

**Issue by dhruvkb** [4lex4/intellij-platform-solarized#18]
With this theme enabled, opening Vim inside the terminal shows a grey background on all the lines, as seen in the screenshot.

<img width="1392" alt="Screenshot 2021-04-03 at 7 46 19 PM" src="https://user-images.githubusercontent.com/16580576/113481091-44d91180-94b5-11eb-8991-6c34c858abac.png">

The solution, for me, was to change the colors manually in the Console Colors section to the correct values from the Solarized page.

<img width="760" alt="Screenshot 2021-04-03 at 7 47 51 PM" src="https://user-images.githubusercontent.com/16580576/113481139-7ce05480-94b5-11eb-906a-b7adc07aad60.png">

But replacing the theme colors with `termcol` colors worked out. I just had to replace the colors in the bright variants with the base colors, violet and orange. Some changes were needed, such as mapping of the names:
| termcol name | IDEA name |
|-|-|
| black | Black |
| brblack | Dark Gray |
| white | Gray |
| brwhite | White |

<img width="1392" alt="Screenshot 2021-04-03 at 7 51 34 PM" src="https://user-images.githubusercontent.com/16580576/113481244-0132d780-94b6-11eb-80ad-da899bac930e.png">

Even iTerm uses bright variants of the colors to hold the termcol colors described in the Solarized table.

<img width="1040" alt="Screenshot 2021-04-03 at 7 53 25 PM" src="https://user-images.githubusercontent.com/16580576/113481282-422aec00-94b6-11eb-9cc1-a5074e715427.png">

**Comment by dhruvkb** [comment]
I understand that the issue has a workaround so solving it might not be a priority, but it would be awesome if this was changed within the theme itself and the workaround wasn't needed in the first place.

**Comment by 4lex4** [comment]
@dhruvkb , just attach Solarized*.iml files in `.<Product><Version>/config/colors` directory (see the location of directories used by IDE to store settings for your OS [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)) and I'll look into it.

**Comment by dhruvkb** [comment]
This is the `Solarized Dark.icls` file from my `colors/` directory.
[Solarized Dark.icls.zip](https://github.com/4lex4/intellij-platform-solarized/files/6962637/Solarized.Dark.icls.zip)
