### ISSUE TITLE
2021.1 inline hints; background color defaults to #EDEDED

### ISSUE THREAD

**Issue by thewisenerd** [4lex4/intellij-platform-solarized#19]
setting it to something sane like #0E3C4A seems better; but I'm assuming with an upgrade this should not be an issue.

posting this here for reference till then.

**Comment by WhiteHatTux** [comment]
@thewisenerd Thank you so much. That was bothering me quite a lot. :-)

**Comment by nreinhardt** [comment]
For example (I believe this is the same issue), this is the appearance in IDEA Ultimate:
![image](https://user-images.githubusercontent.com/51961494/117872040-2a404800-b26c-11eb-9fb9-e3faafa72341.png)
