### ISSUE TITLE
solarized-light shows git log as solarized-dark?

### ISSUE THREAD

**Issue by seanw2020** [4lex4/intellij-platform-solarized#26]
First, thanks for solarized-themes!

On install Intellij Idea Ultimate 211.7628.21 on MacOs 11.4 with `solarized-light`, why is the git log not solarized light too? Can I change it?

![image](https://user-images.githubusercontent.com/18521457/127228603-051df0da-6fde-4734-bc1d-cd33f8d22f67.png)

**Comment by seanw2020** [comment]
Any updates?

**Comment by 4lex4** [comment]
It's not my solarized theme on screenshot despite it's enlisted in your plugin list. Remove/disable all the other theme plugins containing 'Solarizerd Light' or 'Solarized Dark' in their theme names.

**Comment by 4lex4** [comment]
Lamebrain, thats's not my theme and as it's seen on your screenshot you haven't even installed it. Click fukin 'install' button first and remove all the other solarized plugins to avoid conflicts and only then you may post here.

**Comment by seanw2020** [comment]
Indeed, the problem was that I had installed `Solarized Theme` by Tyler Thraikill instead of the plural form `Solarized Themes` by 4lex4 (this repo). After I installed 4lex4's theme, the colors work fine. Sorry for the false alarm.
