### ISSUE TITLE
Solarized light in autocomplete popup with Solarized dark

### ISSUE THREAD

**Issue by martinvisser** [4lex4/intellij-platform-solarized#27]
Just after upgrading to Intellij 2021.2 I noticed the autocomplete popup shows a light theme while I have the dark theme enabled, also the bottom line is in light mode:
![image](https://user-images.githubusercontent.com/3170236/127282990-8269797f-f9b0-466d-999f-c6523c93deee.png)

I really like the theme, so even with this minor inconvenience I'll just keep on going to use it for sure!

Solarized Themes version: 2.3.0

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4

**Comment by martinvisser** [comment]
I tested this on an Ubuntu machine with the same Intellij version and there is works just fine. Also reinstalled the theme to see it that would resolve it but no luck unfortunately.

**Comment by kgreulich** [comment]
Same problem since intellij 2021.2 update. macOS

**Comment by wheredoipressnow** [comment]
Same issue. Windows 10. Only since IDE upgrade. Standard troubleshooting did not help.

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021

**Comment by kgreulich** [comment]
I previously was on IntelliJ's beta program and noticed the problem before. Hoped this will be fixed for 2021.2 release. So I am pretty sure the issue came up with latest IDE update.

**Comment by HeyBanditoz** [comment]
I noticed the same thing on what type is returned on each line here:
![idea64_2xa19Vbu2K](https://user-images.githubusercontent.com/7574664/127752815-5d729fbb-db74-46e7-adde-7c1ae3166cf5.png)
The text is hard to read.

**Comment by Strate** [comment]
I noticed similar problem, but with solarized light theme.

Looks like popup background comes from system light theme

![image](https://user-images.githubusercontent.com/392644/128079178-b0ba8c8d-7b5b-4e0d-a9f8-c74235abdc87.png)

**Comment by Strate** [comment]
I found a workaround!

Go to Preferences -> Editor -> Color Scheme -> General.

Choose from TreeView "Popups And Hints", then go to "Documentation", copy background color from there.
Then go to "Completion", and paste background color there.

![image](https://user-images.githubusercontent.com/392644/128081901-9cd40974-f060-4e99-a34d-da2fda3365fa.png)
