### ISSUE TITLE
An issue with Rider editor tabs

### ISSUE THREAD

**Issue by postmeJ** [4lex4/intellij-platform-solarized#7]
Thank you! But, Could you change the tab color?
![image](https://user-images.githubusercontent.com/25760218/62880954-37f82f00-bd61-11e9-8be7-715c8873f72c.png)

**Comment by 4lex4** [comment]
Just checked on Rider 2019.2, the tabs are OK:  

![rider_tabs](https://user-images.githubusercontent.com/16573106/62989020-1d03e880-be4f-11e9-9215-9e9a1ceeab2a.png)

<br/>
What the IDE version do you use?

**Comment by 4lex4** [comment]
Just checked on Rider 2019.2, the tabs are OK:  

![rider_tabs](https://user-images.githubusercontent.com/16573106/62989020-1d03e880-be4f-11e9-9215-9e9a1ceeab2a.png)

<br/>
What IDE version are you using?
