### ISSUE TITLE
What's the font used in the screentshot?

### ISSUE THREAD

**Issue by xjj59307** [4lex4/intellij-platform-solarized#8]
Could you kindly let me know the font used in the following screenshot?
It looks great to me!

![62012485-9cc35f00-b18f-11e9-9a3d-61dc7d9a41f2](https://user-images.githubusercontent.com/1174232/63219101-bb70b080-c1a5-11e9-8698-981eb88e11ed.png)

**Comment by 4lex4** [comment]
Pragmata Pro.  
Mail me and I'll send you that. ;)
